import {Montserrat} from 'next/font/google'
import './globals.css'
import Navbar from "@/app/ui/Navbar"
import Link from "next/link";

const monsterrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={monsterrat.className}>
            <Navbar />
            {children}
        </body>
    </html>
  )
}
